version: "3"
services:
  conventionbot-server:
    container_name: conventionbot-server
    image: conventionbot-server
    restart: always
    build: .
    ports:
      - "8080:8080"
    links:
      - mongo
    networks:
      - conventionbot-network
    depends_on:
      - mongo
      - mongo-express

  mongo:
    container_name: mongo
    image: mongo:latest
    volumes:
      - type: volume
        source: MONGO_DATA
        target: /data/db
      - type: volume
        source: MONGO_CONFIG
        target: /data/configdb
      - type: volume
        source: MONGO_LOG
        target: /var/log/mongodb
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: conventionbot-server
    networks:
      - conventionbot-network

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: "27017"
      ME_CONFIG_MONGODB_URL: mongodb://0.0.0.0:27017
    networks:
      - conventionbot-network

networks:
  conventionbot-network:
    driver: bridge
    name: conventionbot-network

volumes:
  MONGO_DATA:
  MONGO_CONFIG:
  MONGO_LOG:
